config/routes.rb
Rails.application.routes.draw do
  resources :useflags
  get 'index/index'
  resources :abouts
  resources :changes
  resources :versions
  resources :packages
  resources :categories

  namespace :api do
    resources :categories
    resources :packages
  end
end

app/controllers/changes_controller.rb
class ChangesController < ApplicationController
  before_action :set_change, only: [:show, :edit, :update, :destroy]

  # GET /changes
  def index
    @changes = Change.all
  end

  # GET /changes/1
  def show
  end

  # GET /changes/new
  def new
    @change = Change.new
  end

  # GET /changes/1/edit
  def edit
  end

  # POST /changes
  def create
    @change = Change.new(change_params)

    if @change.save
      redirect_to @change, notice: 'Change was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /changes/1
  def update
    if @change.update(change_params)
      redirect_to @change, notice: 'Change was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /changes/1
  def destroy
    @change.destroy
    redirect_to changes_url, notice: 'Change was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_change
      @change = Change.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def change_params
      params.fetch(:change, {})
    end
end

app/helpers/changes_helper.rb
module ChangesHelper
end

app/views/changes/_form.html.erb
<%= form_with(model: change, local: true) do |form| %>
  <% if change.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(change.errors.count, "error") %> prohibited this change from being saved:</h2>

      <ul>
      <% change.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/changes/edit.html.erb
<h1>Editing Change</h1>

<%= render 'form', change: @change %>

<%= link_to 'Show', @change %> |
<%= link_to 'Back', changes_path %>

app/views/changes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Changes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @changes.each do |change| %>
      <tr>
        <td><%= link_to 'Show', change %></td>
        <td><%= link_to 'Edit', edit_change_path(change) %></td>
        <td><%= link_to 'Destroy', change, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Change', new_change_path %>

app/views/changes/new.html.erb
<h1>New Change</h1>

<%= render 'form', change: @change %>

<%= link_to 'Back', changes_path %>

app/views/changes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_change_path(@change) %> |
<%= link_to 'Back', changes_path %>