config/routes.rb
Rails.application.routes.draw do
  resources :useflags
  get 'index/index'
  resources :abouts
  resources :changes
  resources :versions
  resources :packages
  resources :categories

  namespace :api do
    resources :categories
    resources :packages
  end
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  before_action :set_version, only: [:show, :edit, :update, :destroy]

  # GET /versions
  def index
    @versions = Version.all
  end

  # GET /versions/1
  def show
  end

  # GET /versions/new
  def new
    @version = Version.new
  end

  # GET /versions/1/edit
  def edit
  end

  # POST /versions
  def create
    @version = Version.new(version_params)

    if @version.save
      redirect_to @version, notice: 'Version was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /versions/1
  def update
    if @version.update(version_params)
      redirect_to @version, notice: 'Version was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /versions/1
  def destroy
    @version.destroy
    redirect_to versions_url, notice: 'Version was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_version
      @version = Version.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def version_params
      params.fetch(:version, {})
    end
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/versions/_form.html.erb
<%= form_with(model: version, local: true) do |form| %>
  <% if version.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(version.errors.count, "error") %> prohibited this version from being saved:</h2>

      <ul>
      <% version.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/versions/edit.html.erb
<h1>Editing Version</h1>

<%= render 'form', version: @version %>

<%= link_to 'Show', @version %> |
<%= link_to 'Back', versions_path %>

app/views/versions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Versions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @versions.each do |version| %>
      <tr>
        <td><%= link_to 'Show', version %></td>
        <td><%= link_to 'Edit', edit_version_path(version) %></td>
        <td><%= link_to 'Destroy', version, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Version', new_version_path %>

app/views/versions/new.html.erb
<h1>New Version</h1>

<%= render 'form', version: @version %>

<%= link_to 'Back', versions_path %>

app/views/versions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_version_path(@version) %> |
<%= link_to 'Back', versions_path %>