config/routes.rb
Rails.application.routes.draw do
  resources :useflags
  get 'index/index'
  resources :abouts
  resources :changes
  resources :versions
  resources :packages
  resources :categories

  namespace :api do
    resources :categories
    resources :packages
  end
end

app/models/useflag.rb
class Package
  include ActiveModel::Model # supplies some methods necessary for form helpers
  include ActiveModel::Validations # provides error message caching and validations methods

  ATTRIBUTES = [:name,
                :description,
                :atom,
                :scope,
                :use_expand_prefix]

  attr_accessor(*ATTRIBUTES)
  attr_reader :attributes

  def all_fields
    [:name, :description, :atom, :scope, :use_expand_prefix]
  end

  def to_param
    name
  end

  def strip_use_expand
    name.gsub(use_expand_prefix + '_', '')
  end

  class << self
    # Retrieves all flags sorted by their state
    def get_flags(name)
      result = { local: {}, global: [], use_expand: [] }

      find_all_by(:name, name).each do |flag|
        case flag.scope
        when 'local'
          result[:local][flag.atom] = flag
        when 'global'
          result[:global] << flag
        when 'use_expand'
          result[:use_expand] << flag
        end
      end

      result
    end

    def suggest(q)
      results = Useflag.search(
        size: 20,
        query: { match_phrase_prefix: { name: q } }
      )

      processed_results = {}
      results.each do |result|
        if processed_results.key? result.name
          processed_results[result.name] = {
            name: result.name,
            description: '(multiple definitions)',
            scope: 'multi'
          }
        else
          processed_results[result.name] = result
        end
      end

      processed_results.values.sort { |a, b| a[:name].length <=> b[:name].length }
    end

    # Loads the local USE flags for a given package in a name -> model hash
    #
    # @param [String] atom Package to find flags for
    # @return [Hash]
    def local_for(atom)
      map_by_name find_all_by(:atom, atom)
    end

    # Maps the global USE flags in the index by their name
    # This is expensive!
    #
    def global
      map_by_name find_all_by(:scope, 'global')
    end

    # Maps the USE_EXPAND variables in the index by their name
    #
    def use_expand
      map_by_name find_all_by(:scope, 'use_expand')
    end

    def initialize(attr={})
      attr.each do |k,v|
        if ATTRIBUTES.include?(k.to_sym)
          send("#{k}=", v)
        end
      end
    end

    def attributes
      ATTRIBUTES.inject({}) do |hash, attr|
        if value = send(attr)
          hash[attr] = value
        end
        hash
      end
    end
    alias :to_hash :attributes

    private

    def map_by_name(collection)
      map = {}

      collection.each do |item|
        map[item.name] = item
      end

      map
    end
  end
end

app/controllers/useflags_controller.rb
class UseflagsController < ApplicationController
  before_action :set_useflag, only: [:show, :edit, :update, :destroy]

  # GET /useflags
  def index
    @useflags = Useflag.all
  end

  # GET /useflags/1
  def show
  end

  # GET /useflags/new
  def new
    @useflag = Useflag.new
  end

  # GET /useflags/1/edit
  def edit
  end

  # POST /useflags
  def create
    @useflag = Useflag.new(useflag_params)

    if @useflag.save
      redirect_to @useflag, notice: 'Useflag was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /useflags/1
  def update
    if @useflag.update(useflag_params)
      redirect_to @useflag, notice: 'Useflag was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /useflags/1
  def destroy
    @useflag.destroy
    redirect_to useflags_url, notice: 'Useflag was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_useflag
      @useflag = Useflag.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def useflag_params
      params.fetch(:useflag, {})
    end
end

app/helpers/useflags_helper.rb
module UseflagsHelper
end

app/views/useflags/_form.html.erb
<%= form_with(model: useflag, local: true) do |form| %>
  <% if useflag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(useflag.errors.count, "error") %> prohibited this useflag from being saved:</h2>

      <ul>
      <% useflag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/useflags/edit.html.erb
<h1>Editing Useflag</h1>

<%= render 'form', useflag: @useflag %>

<%= link_to 'Show', @useflag %> |
<%= link_to 'Back', useflags_path %>

app/views/useflags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Useflags</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @useflags.each do |useflag| %>
      <tr>
        <td><%= link_to 'Show', useflag %></td>
        <td><%= link_to 'Edit', edit_useflag_path(useflag) %></td>
        <td><%= link_to 'Destroy', useflag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Useflag', new_useflag_path %>

app/views/useflags/new.html.erb
<h1>New Useflag</h1>

<%= render 'form', useflag: @useflag %>

<%= link_to 'Back', useflags_path %>

app/views/useflags/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_useflag_path(@useflag) %> |
<%= link_to 'Back', useflags_path %>