config/routes.rb
Rails.application.routes.draw do
  resources :useflags
  get 'index/index'
  resources :abouts
  resources :changes
  resources :versions
  resources :packages
  resources :categories

  namespace :api do
    resources :categories
    resources :packages
  end
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  before_action :set_about, only: [:show, :edit, :update, :destroy]

  # GET /abouts
  def index
    @abouts = About.all
  end

  # GET /abouts/1
  def show
  end

  # GET /abouts/new
  def new
    @about = About.new
  end

  # GET /abouts/1/edit
  def edit
  end

  # POST /abouts
  def create
    @about = About.new(about_params)

    if @about.save
      redirect_to @about, notice: 'About was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /abouts/1
  def update
    if @about.update(about_params)
      redirect_to @about, notice: 'About was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /abouts/1
  def destroy
    @about.destroy
    redirect_to abouts_url, notice: 'About was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_about
      @about = About.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def about_params
      params.fetch(:about, {})
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/views/about/_form.html.erb
<%= form_with(model: about, local: true) do |form| %>
  <% if about.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(about.errors.count, "error") %> prohibited this about from being saved:</h2>

      <ul>
      <% about.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/about/edit.html.erb
<h1>Editing About</h1>

<%= render 'form', about: @about %>

<%= link_to 'Show', @about %> |
<%= link_to 'Back', abouts_path %>

app/views/about/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Abouts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @abouts.each do |about| %>
      <tr>
        <td><%= link_to 'Show', about %></td>
        <td><%= link_to 'Edit', edit_about_path(about) %></td>
        <td><%= link_to 'Destroy', about, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New About', new_about_path %>

app/views/about/new.html.erb
<h1>New About</h1>

<%= render 'form', about: @about %>

<%= link_to 'Back', abouts_path %>

app/views/about/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_about_path(@about) %> |
<%= link_to 'Back', abouts_path %>